<?php
/**
 * @package WordPress
 * @subpackage Adamantium - Starter Kit
 * @author Bitopia Digital Agency
 */

	/*
		If you do not know what you do, DO NOT EDIT THIS FILE
	*/

		define("THEME_DIR", get_template_directory_uri());

	// ADAMANTIUM CORE
		/* Do not delete this line! */
		require (TEMPLATEPATH . '/includes/adamantium.php');


	// CUSTOM POST TYPES
		/* If you are not using Custom Post Types can comment this line */
		require (TEMPLATEPATH . '/includes/custom-post-types.php'); 


	// MENUS
		/* If you are not using Menus can comment this line */
		require (TEMPLATEPATH . '/includes/menus.php');


	// EXTRA
		/* All that considered as an extra or utility that is external to WordPress and not default, you should put in the "Extra" Folder */
		require (TEMPLATEPATH . '/includes/extra/content-limit.php');


	// ENQUEUE SCRIPTS & STYLES
		function adamantium_scripts_and_styles() {
		if ( !is_admin() ) { // this if statement will insure the following code only gets added to your wp site and not the admin page cause your code has no business in the admin page right unless that's your intentions
		/* STYLES */
			// Main stylesheet
			//wp_register_style ('adamantium-stylesheet', get_stylesheet_directory_uri() . '/style.css', array(), '', 'all' );
			//wp_enqueue_style ('adamantium-stylesheet');

			// comment reply script for threaded comments
		if ( is_singular() AND comments_open() AND (get_option('thread_comments') == 1)) {
			wp_enqueue_script( 'comment-reply' );
		}
	}
}
add_action( 'wp_enqueue_scripts', 'adamantium_scripts_and_styles', 999);

/***************************************************************************************/
function buencafe_scripts() {
	wp_enqueue_style( 'select2-css', get_template_directory_uri() . '/js/select2/css/select2.min.css' );
	wp_enqueue_style( 'fancybox-css', get_template_directory_uri() . '/js/fancybox/jquery.fancybox.min.css' );
	wp_enqueue_script( 'jquery-10', get_template_directory_uri() . '/js/jquery-1.10.2.min.js', array(), '20151215', true );
	wp_enqueue_style( 'bootstrap-css', get_template_directory_uri() . '/css/grid12.css' );
	wp_enqueue_script( 'select2-js', get_template_directory_uri() . '/js/select2/js/select2.full.min.js', array('jquery'), '20151215', true );
	wp_enqueue_script( 'fancybox-js', get_template_directory_uri() . '/js/fancybox/jquery.fancybox.min.js', array('jquery'), '20151215', true );
	wp_enqueue_script( 'form-js', get_template_directory_uri() . '/js/form-contact.js', array(), '20151215', true );
};
add_action( 'wp_enqueue_scripts', 'buencafe_scripts' );
/***************************************************************************************/
?>
<?php 

// custom jquery
//wp_register_script( 'custom_js', get_template_directory_uri() . '/js/jquery.custom.js', array( 'jquery' ), '1.0', TRUE );
//wp_enqueue_script( 'custom_js' );

// validation
wp_register_script( 'validation', 'https://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js', array( 'jquery' ) );
wp_enqueue_script( 'validation' );

function mySearchFilter($query) {
	$post_type = $_GET['post_type'];
	if (!$post_type) {
		$post_type = 'any';
	}
	if ($query->is_search) {
		$query->set('post_type', $post_type);
	};
	return $query;
};

add_filter('pre_get_posts','mySearchFilter');
if ( ! function_exists( 'shape_comment' ) ) :
	/**
	 * Template for comments and pingbacks.
	 *
	 * Used as a callback by wp_list_comments() for displaying the comments.
	 *
	 * @since Shape 1.0
	 */
function shape_comment( $comment, $args, $depth ) {
	$GLOBALS['comment'] = $comment;
	switch ( $comment->comment_type ) :
	case 'pingback' :
	case 'trackback' :
	?>
	<?php
	break;
	default :
	?>

	<article <?php comment_class(); ?> id="comment-<?php comment_ID(); ?>">
		<div class="usuario" alt="Perfil">
			<?php $user = get_user_by( 'id', $comment->user_id );  ?>
			<?php if (get_field('foto_usuario', 'user_'.$user->ID)): ?>
			<img alt="<?php echo $user->user_firstname . ' ' . $user->user_lastname; ?>" src="<?php echo get_field('foto_usuario', 'user_'.$user->ID); ?>">
		<?php else: ?>
		<span><?php echo $user->user_firstname[0] . ' ' . $user->user_lastname[0] ; ?></span>
	<?php endif ?>

</div>
<div class="comentario">
	<?php $user = get_user_by( 'id', $comment->user_id );  ?>
	<h1><strong><?php /*printf( __( '%s'), get_comment_author_link() );*/
	 echo $user->user_firstname . ' ' . $user->user_lastname ; ?></strong><br><?php printf( __( '%1$s'), get_comment_date(), get_comment_time() ); ?></h1>
	<?php comment_text(); ?>
	<?php if (is_user_logged_in()): ?>
	<div class="btn"><?php comment_reply_link( array_merge( $args, array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?></div>
<?php else: ?>
	<?php comment_reply_link( array_merge( $args, array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?>
<?php endif ?>
</div>
</article>

<?php
break;
endswitch;
}
	endif; // ends check for shape_comment()

	add_filter( 'comment_form_defaults', 'remove_textarea' );
	add_action( 'comment_form_top', 'add_textarea' );
	function remove_textarea($defaults) {
		$defaults['comment_field'] = '';
		return $defaults;
	}

	function add_textarea() {
		$user = wp_get_current_user();
			$link_actual = explode("/", get_permalink( $post->ID ));
		    /* Detectar si esta en ingles */
		    if ( in_array("en", $link_actual ) ){
		        $english = true;
		    }
		echo '<div class="usuario">';?>
		<?php if (get_field('foto_usuario', 'user_'.$user->ID)): ?>
		<img alt="<?php echo $user->user_firstname . ' ' . $user->user_lastname; ?>" src="<?php echo get_field('foto_usuario', 'user_'.$user->ID); ?>">
	<?php else: ?>
	<span><?php echo $user->user_firstname[0] . ' ' . $user->user_lastname[0] ; ?></span>
<?php endif ?>
</div><textarea id="comment" name="comment" cols="60" rows="6" class="comentario" placeholder="<?php if(!$english)echo 'Escribe tu comentario'; else echo 'Write your comment' ?>" aria-required="true" required></textarea>;
<?php
}

add_filter('comment_reply_link', 'replace_reply_link_class');
function replace_reply_link_class($class){
	$class = str_replace("class='comment-reply-link", "class='reply responder", $class);
	return $class;
}
function tml_new_user_registered( $user_id ) {
	wp_set_auth_cookie( $user_id, false, is_ssl() );
    //wp_redirect( admin_url( 'profile.php' ) );
	exit;
}
add_action( 'tml_new_user_registered', 'tml_new_user_registered' );
function get_terms_dropdown($taxonomies, $args){
	$myterms = get_terms($taxonomies, $args);
	  //$output ="<select name='tipo'>";
	foreach($myterms as $term){
		$root_url = get_bloginfo('url');
		$term_taxonomy=$term->taxonomy;
		$term_slug=$term->slug;
		$term_name =$term->name;
		$term_id =$term->term_id;
		$output .="<option value='".$term_slug."'>".$term_name."</option>";
	}
	  //$output .="</select>";
	return $output;
}

function get_consigna_dropdown($taxonomies, $args){
	$myterms = get_terms($taxonomies, $args);
	foreach($myterms as $term){
		$root_url = get_bloginfo('url');
		$term_taxonomy=$term->taxonomy;
		$term_slug=$term->slug;
		$term_name =$term->name;
		$term_description =$term->description;
		$term_id =$term->term_id;
		$text = get_field('texto_combo',$term->taxonomy.'_'.$term->term_id);
		$output .="<option value='".$term_slug."'>".$text."</option>";
	}
	return $output;
}

function getCountCatFav($cptFav) {
	$have_favorite_posts = false;
	$favorite_post_ids = wpfp_get_users_favorites();
	if (! empty($favorite_post_ids)) {
		$fp_query = new WP_Query(array(
			'post_type' => $cptFav,
			'post__in' => $favorite_post_ids
			));
		if ($fp_query->have_posts()) {
			$have_favorite_posts = true;
			$count = 0;
			while ($fp_query->have_posts()) : $fp_query->the_post();
			if ('publish' === get_post_status(get_the_ID())) {

				$count++;

			}
			endwhile;
	            //echo $count;
			return $count;
		}
	}
	if (! $have_favorite_posts) {
		return 0;
	}

}

function admin_default_page() {
	return home_url();
}
add_filter('login_redirect', 'admin_default_page');

function revcon_change_post_label() {
	global $menu;
	global $submenu;
	$menu[5][0] = 'Actualidad';
	$submenu['edit.php'][5][0] = 'Todas las Actualidad';
	$submenu['edit.php'][10][0] = 'Agregar Actualidad';
	$submenu['edit.php'][16][0] = 'Actualidad Tags';
	echo '';
}
// function revcon_change_post_object() {
// 	global $wp_post_types;
// 	$labels = &$wp_post_types['post']->labels;
// 	$labels->name = 'Actualidad';
// 	$labels->singular_name = 'Actualidad';
// 	$labels->add_new = 'Agregar Actualidad';
// 	$labels->add_new_item = 'Agregar Actualidad';
// 	$labels->edit_item = 'Editar Actualidad';
// 	$labels->new_item = 'Actualidad';
// 	$labels->view_item = 'Ver Actualidad';
// 	$labels->search_items = 'Buscar Actualidad';
// 	$labels->not_found = 'No Actualidad found';
// 	$labels->not_found_in_trash = 'No Actualidad en la papelera';
// 	$labels->all_items = 'Todo Actualidad';
// 	$labels->menu_name = 'Actualidad';
// 	$labels->name_admin_bar = 'Actualidad';
// }

// add_action( 'admin_menu', 'revcon_change_post_label' );
// add_action( 'init', 'revcon_change_post_object' );




// function updateMetaHijos($id, $numhijo) {
// 	update_user_meta($id, 'user_nombre_hijo'.$numhijo.'', $_POST['user_nombre_hijo'.$numhijo.'']);
// 	update_user_meta($id, 'user_fecha_hijo'.$numhijo.'', $_POST['user_fecha_hijo'.$numhijo.'']);
// 		//update_user_meta($id, 'user_dni_hijo'.$numhijo.'', $_POST['user_dni_hijo'.$numhijo.'']);
// }




// add_action( 'admin_menu', 'datosContacto' );
// function datosContacto() {
// 	add_options_page( 'Datos Formulario', 'Datos Formulario', 'manage_options', 'my-unique-identifier', 'datosFormularioCotacto' );
// }
// function datosFormularioCotacto() {
// 	if ( !current_user_can( 'manage_options' ) )  {
// 		wp_die( __( 'Permisos insuficientes' ) );
// 	}

// 	echo "<h1>Consultas - Formulario de Contacto</h1>";
// 	global $wpdb;

// 	$rows = $wpdb->get_results("select * from wp_formcontacto");

// 	foreach ($rows as $obj) {
// 		echo $obj->id."<br />";
// 		echo $obj->nombre."<br />";
// 		echo $obj->email."<br />";
// 		echo $obj->comentario."<br />";
// 		echo "<hr />";
// 	}

// 	echo '<a href="'.get_bloginfo('url').'/wp-content/themes/theme_arcor/exportar.php?descarga=contacto">DESCARGAR EXCEL</a>';
// }


// run before ACF saves the $_POST['fields'] data
//add_action('acf/save_post', 'my_acf_save_post', 1);	
// function my_acf_save_post( $post_id ){
// 	// vars
// 	$fields = false;
// 	$post = get_post( $post_id  ); 
//  //here i added a if stattement so the code runs only for a defined post //type you can change "pompitup_product" or delet that if statement
// 	if(get_post_type( $post_id ) === "comunidad"){
// 	//check if Fields have been posted
// 		if( isset($_POST['fields']) ){
// 		//store the true/false field on a variable (change 
//                 //the "Field_xxx" id by yours)
// 			$feature_product = $_POST['fields']["field_560dd4aa58fea"];


// 			//check if the true/false field is true
// 			if( $feature_product == 1 ){
// 				global $wpdb;

// 				$wpdb->insert( $table_name, array( 
// 					'user_id' => $post->post_author,
// 					'post_ID' => $post_id,
// 					'comment_ID' => 0
// 					) );
// 				require_once( ABSPATH . 'PHPMailer/PHPMailerAutoload.php');

// 				$mail = new PHPMailer;

//   $mail->isSMTP();                                      // Set mailer to use SMTP
//   $mail->Host = 'smtp.gmail.com';                       // Specify main and backup server
//   $mail->SMTPAuth = true;                               // Enable SMTP authentication
//   $mail->Username = 'contacto@cumplearcor.com';                   // SMTP username
//   $mail->Password = 'Contacto!!2015.cumple';               // SMTP password
//   $mail->SMTPSecure = 'tls';                            // Enable encryption, 'ssl' also accepted
//   $mail->Port = 587;                                    //Set the SMTP port number - 587 for authenticated TLS
//   $mail->setFrom('contacto@cumplearcor.com', 'Cumple Arcor');     //Set who the message is to be sent from
//   $user_info = get_userdata($post->post_author);
//   $mail->addAddress($user_info->user_email);  // Add a recipient
// //$mail->AddBCC('nferreyra@bitopia.com.ar');

//   $message = '<img src="http://www.cumplearcor.com/cumplearcor.jpg"><br><br><br><p style="font-family: Calibri, Arial, Helvetica, sans-serif;">¡Felicitaciones '.$user_info->first_name.'! tu <a style="font-family: Calibri, Arial, Helvetica, sans-serif;" href="'.get_post_permalink($info->comment_post_ID ).'">publicaci&oacute;n</a> fue marcada como nuestra Favorita.<br><br>¡Gracias por formar parte de nuestra Comunidad!<br><br>Conocé las mejores ideas para los festejos de cumple en <a style="font-family: Calibri, Arial, Helvetica, sans-serif;" href="http://www.cumplearcor.com">www.cumplearcor.com</a>.</p>';
//   $subject = 'Nueva notificación en la Comunidad Cumple Arcor';
//   $mail->Subject =  $subject;
//   $mail->Body = $message;

//   $mail->CharSet = 'UTF-8';
//   $mail->IsHTML(true);   
//   $mail->header  = 'MIME-Version: 1.0' . "\r\n";

//   $mail->header .= 'Content-type: text/html; charset=UTF-8' . "\r\n";

//   $mail->header .= 'From: '.$from_name.' <'.$from_email.'>';
//   $mail->send();



// 		}//end isset($_POST['fields'])---->for post

// 		$feature_product = $_POST['fields']["field_560dd47a58fe8"];
// 		if( $feature_product == 1 ){
// 			global $wpdb;

// 			$wpdb->insert( $table_name, array( 
// 				'user_id' => $post->post_author,
// 				'post_ID' => $post_id,
// 				'comment_ID' => 0
// 				) );
// 			require_once( ABSPATH . 'PHPMailer/PHPMailerAutoload.php');

// 			$mail = new PHPMailer;

//   $mail->isSMTP();                                      // Set mailer to use SMTP
//   $mail->Host = 'smtp.gmail.com';                       // Specify main and backup server
//   $mail->SMTPAuth = true;                               // Enable SMTP authentication
//   $mail->Username = 'contacto@cumplearcor.com';                   // SMTP username
//   $mail->Password = 'Contacto!!2015.cumple';               // SMTP password
//   $mail->SMTPSecure = 'tls';                            // Enable encryption, 'ssl' also accepted
//   $mail->Port = 587;                                    //Set the SMTP port number - 587 for authenticated TLS
//   $mail->setFrom('contacto@cumplearcor.com', 'Cumple Arcor');     //Set who the message is to be sent from
//   $user_info = get_userdata($post->post_author);
// //$mail->AddBCC('nferreyra@bitopia.com.ar');

//   $mail->addAddress($user_info->user_email);  // Add a recipient
//  // $mail->addAddress('nferreyra@bitopia.com.ar');  // Add a recipient
//   $message = '<img src="http://www.cumplearcor.com/cumplearcor.jpg"><br><br><br><p style="font-family: Calibri, Arial, Helvetica, sans-serif;">¡Felicitaciones '.$user_info->first_name.'! Fuiste la <a style="font-family: Calibri, Arial, Helvetica, sans-serif;" href="'.get_post_permalink($info->comment_post_ID ).'">ganadora</a> de la consigna de este mes.<br><br>Nos encantó tu propuesta, gracias por compartirla con nuestra Comunidad.<br><br>Conocé las mejores ideas para los festejos de cumple en <a style="font-family: Calibri, Arial, Helvetica, sans-serif;" href="http://www.cumplearcor.com">www.cumplearcor.com</a>.</p>';

//   $subject = 'Nueva notificación en la Comunidad Cumple Arcor';

//   $mail->Subject =  $subject;
//   $mail->Body = $message;

//   $mail->CharSet = 'UTF-8';
//   $mail->IsHTML(true);   
//   $mail->header  = 'MIME-Version: 1.0' . "\r\n";

//   $mail->header .= 'Content-type: text/html; charset=UTF-8' . "\r\n";

//   $mail->header .= 'From: '.$from_name.' <'.$from_email.'>';
//   $mail->send();


		//}//end isset($_POST['fields'])---->for post
 	//}//end check if post-type== pompitup_product


//}//end my_acf_save_post
//}//end my_acf_save_post



add_action( 'admin_menu', 'datosNewsletter' );
function datosNewsletter() {
	add_options_page( 'Datos Newsletter', 'Datos Newsletter', 'manage_options', 'my-unique-identifier-two', 'datosFormularioNewsletter' );
}
function datosFormularioNewsletter() {
	if ( !current_user_can( 'manage_options' ) )  {
		wp_die( __( 'Permisos insuficientes' ) );
	}

	echo "<h1>Suscriptores la newsletter</h1>";
	global $wpdb;

	$rows = $wpdb->get_results("select * from wp_newsletter");

	foreach ($rows as $obj) {
		echo $obj->id."<br />";
		echo $obj->email."<br />";
		echo "<hr />";
	}

	echo '<a href="'.get_bloginfo('url').'/wp-content/themes/theme_arcor/exportar.php?descarga=newsletter">DESCARGAR EXCEL</a>';
}
function new_excerpt_length($length) {
	return 1000;
}
add_filter('excerpt_length', 'new_excerpt_length');

function my_add_excerpts_to_pages() {
	add_post_type_support( 'page',array( 'excerpt', 'tags' ));
}
add_action( 'init', 'my_add_excerpts_to_pages' );
function tags_support_all() {
	register_taxonomy_for_object_type('post_tag', 'page');
}

// ensure all tags are included in queries
function tags_support_query($wp_query) {
	if ($wp_query->get('tag')) $wp_query->set('post_type', 'any');
}

// tag hooks
add_action('init', 'tags_support_all');
add_action('pre_get_posts', 'tags_support_query');

/* CANTIDAD DE VISITAS */
function getPostViews($postID){ // obtengo el id de la entrada
	$count_key = 'post_views_count';
	$count = get_post_meta($postID, $count_key, true);
	if($count==''){
		delete_post_meta($postID, $count_key);
		add_post_meta($postID, $count_key, '0');
		return "0";
	}
	return $count;
}

function setPostViews($postID) { // obtengo el id de la entrada
	$count_key = 'post_views_count';
	$count = get_post_meta($postID, $count_key, true);
	if($count==''){
		$count = 0;
		delete_post_meta($postID, $count_key);
		add_post_meta($postID, $count_key, '0');
	}else{
		$count++;
		update_post_meta($postID, $count_key, $count);
	}
}

/* Image Size */
if ( function_exists( 'add_image_size' ) ) {
add_image_size( 'Mysize', 375, 241, true );

}
add_filter('image_size_names_choose', 'my_image_sizes');
function my_image_sizes( $sizes ) {
    return array_merge( $sizes, array(
        'Mysize' => __('Mysize'),
    ) );
}

/* Cierre de sesion */
add_action('wp_logout','go_home');
function go_home(){
	wp_redirect( home_url() );
	exit();
}

/* Restringir acceso a la pagina de administrador */
function restringir_login(){
    global $current_user;
    get_currentuserinfo();
    if ($current_user->user_level <  4) { //si no es admin no entra
        wp_redirect( get_bloginfo('url') );
        exit;
    }
}
add_action('admin_init', 'restringir_login', 1);

/* COMENTARIOS */

add_filter( 'comment_form_defaults', 'my_custom_phrase' );
function my_custom_phrase( $array ){
		$link_actual = explode("/", get_permalink( $post->ID ));
    /* Detectar si esta en ingles */
    if ( in_array("en", $link_actual ) ){
        $english = true;
    }
    if(!$english){
		$array['must_log_in'] = sprintf( __( '<p class="must-log-in"> Disculpá, debes  <a href="%s">iniciar sesion</a> para escribir un comentario.</p>' ), wp_login_url( get_permalink() ) );	
    }
    else{
    	$array['must_log_in'] = sprintf( __( '<p class="must-log-in">Please <a href="%s">log in</a> to post a comment.</p>' ), wp_login_url( get_permalink() ) );
    }
	return $array;
}
/*Captcha forms*/
function add_custom_recaptcha_forms( $forms ) {
$forms['my_custom_form'] = array( "form_name" => "Custom Form Name" );
return $forms;
}
add_filter( 'gglcptch_add_custom_form', 'add_custom_recaptcha_forms' );

// Register a new shortcode: [cr_custom_registration]
add_shortcode( 'cr_custom_registration', 'custom_registration_shortcode' );

// The callback function that will replace [book]
function custom_registration_shortcode() {
    ob_start();
    custom_registration_function();
    return ob_get_clean();
}